# Generated by Django 3.1 on 2022-08-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='RedesSocialesCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'redessocialescatalogo',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFavorita', models.BooleanField(default=0)),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('encuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='encuestas.encuesta')),
                ('redSocial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='encuestas.redessocialescatalogo')),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
    ]
